#! /bin/sh
#
# avahi-dnsconfd     avahi dns configuration daemon
#                               Daemon for ZeroConf
#
# Author:		Steev Klimaszewski <steev@steev.net>

DAEMON=/usr/bin/avahi-dnsconfd

depend () {
	need net
	after avahi-daemon
}

start() {
	ebegin "Starting avahi-dnsconfd"
        $DAEMON -D
	eend $?
}

stop() {
	ebegin "Stopping avahi-dnsconfd"
	$DAEMON -k || /bin/true
	eend $?
}

reload() {
	ebegin "Reloading avahi-dnsconfd"
        $DAEMON -r
	eend $?
}
