---
name: "Codespell"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.language }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      actions: read
      security-events: write

    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Do CodeSpell check
      uses: codespell-project/actions-codespell@v2
